config/routes.rb
Rails.application.routes.draw do
	root 'books#index'

	#books
	get 'books' => 'books#index', :as => 'books'
	post 'books' => 'books#index', :as => 'books_post'

	#loans
	post 'loans/create/:book_id	' => 'loans#create', :as => 'create_loan'
	get 'loans/new/:book_id' => 'loans#new', :as => 'new_loan'
	get 'loans/index' => 'loans#index', :as => 'loan_index'
	post 'loans/pre_return_book' => 'loans#pre_return_book', :as => 'loans_pre_return_book'
	post'loans/return_book' => 'loans#return_book', :as => 'loans_return_book'
	get 'loans' => 'loans#index', :as => 'loans'
	get 'return_robot/:case_id' => 'loans#return_robot', :as =>'return_robot'

	#robot
	get 'wait_robot/:case_id' => 'robot#wait_robot', :as =>'wait_robot'
	

	resources :books, except:[:index, :create, :update, :destroy]
end

app/controllers/robot_controller.rb
class RobotController < ApplicationController
	include ApplicationHelper

	def wait_robot
	end

end

app/views/robot/wait_robot.html.erb
<div class="">
  <div class="page-title">
    <div class="title_left">
    <h3>Operação em andamento...</h3>
    </div>
  </div>

  <div class="clearfix"></div>

<div class="modal show" id="processing-modal" role="dialog">
  <div class="modal-dialog">
      <div class="modal-content">
          <div class="modal-body">
              <div class="text-center">
                  <img src="http://www.travislayne.com/images/loading.gif" class="icon" />
                  <h3>Operação em andamento...</h3>
                  <h2>O robô está realizando a operação. Quando ele chegar na bancada, clique em continuar para finalizar a operação.</h2>
                  <%= link_to '<i aria-hidden="true"></i> Continuar</a>'.html_safe, return_robot_path("#{params[:case_id]}"), class: "btn btn-md btn-success", onclick: "return confirm('O robô já está na bancada?');" %> 
              </div>
          </div>
      </div>
  </div>
</div>


</div>