config/routes.rb
Rails.application.routes.draw do
	root 'books#index'

	#books
	get 'books' => 'books#index', :as => 'books'
	post 'books' => 'books#index', :as => 'books_post'

	#loans
	post 'loans/create/:book_id	' => 'loans#create', :as => 'create_loan'
	get 'loans/new/:book_id' => 'loans#new', :as => 'new_loan'
	get 'loans/index' => 'loans#index', :as => 'loan_index'
	post 'loans/pre_return_book' => 'loans#pre_return_book', :as => 'loans_pre_return_book'
	post'loans/return_book' => 'loans#return_book', :as => 'loans_return_book'
	get 'loans' => 'loans#index', :as => 'loans'
	get 'return_robot/:case_id' => 'loans#return_robot', :as =>'return_robot'

	#robot
	get 'wait_robot/:case_id' => 'robot#wait_robot', :as =>'wait_robot'
	

	resources :books, except:[:index, :create, :update, :destroy]
end

app/models/book.rb
class Book < ApplicationRecord
	has_many :schedules, :dependent => :destroy
	has_one :loan
	has_one :case
	belongs_to :case
	#title
	validates_length_of :title,
						:within => 1..100, 
						:too_short => "Título tem que ter no mínimo 1 caracter",
				  		:too_long => "Título tem que ter no máximo 100 caracteres"
	validates :title, :presence => { :message => "Informe o título do livro" }
	
	#subtitle
	validates :subtitle, length: { maximum: 100, message: "Subtítulo tem que ter no máximo 100 caracteres"}

	#author_one
	validates_length_of :author_one,
						:within => 3..100, 
						:too_short => "Primeiro autor tem que ter no mínimo 3 caracteres",
				  		:too_long => "Primeiro autor tem que ter no máximo 100 caracteres"
	validates :author_one, :presence => { :message => "Informe o nome do primeiro autor"}
	
	
	#author_two
	validates :author_two, length: { maximum: 100, message: "Segundo autor tem que ter no máximo 100 caracteres"}

	#author_three
	validates :author_three, length: { maximum: 100, message: "Terceiro autor tem que ter no máximo 100 caracteres"}

	#publisher
	validates_length_of :publisher,
						:within => 2..20, 
						:too_short => "Editora tem que ter no mínimo 2 caracteres",
				  		:too_long => "Editora tem que ter no máximo 20 caracteres"
	validates :publisher, :presence => { :message => "Informe a editora do livro"}

	#year
	validates_length_of :year,
						:within => 4..4, 
						:too_short => "Ano tem que ter no mínimo 4 caracteres",
				  		:too_long => "Ano tem que ter no máximo 4 caracteres"
	validates :year, :presence => {:message => "Informe o ano do livro"}
	
	#city
	validates_length_of :city,
						:within => 3..20, 
						:too_short => "Cidade tem que ter no mínimo 3 caracteres",
				  		:too_long => "Cidade tem que ter no máximo 20 caracteres"
	validates :city, :presence => { :message => "Informe o local do livro"}
	

	#edition
	validates_length_of :edition,
						:within => 1..3, 
						:too_short => "Edição tem que ter no mínimo 1 caracter",
				  		:too_long => "Edição tem que ter no máximo 3 caracteres"
	validates :edition, :presence => { :message => "Informe a edição do livro"}

	#volume
	validates :volume, length: { maximum: 3, message: "Volume tem que ter no máximo 3 caracteres"}

	#pages
	validates_length_of :pages,
						:within => 1..5, 
						:too_short => "Página tem que ter no mínimo 1 caracteres",
				  		:too_long => "Página tem que ter no máximo 5 caracteres"
	validates :pages, :presence => { :message => "Informe as páginas do livro"}

	#isbn
	validates_length_of :ISBN,
						:within => 1..13, 
						:too_short => "ISBN tem que ter no mínimo 1 caracteres",
				  		:too_long => "ISBN tem que ter no máximo 13 caracteres"
	validates :ISBN, :presence => {:message => "Informe o ISBN do livro" }

	#barcode
	validates_length_of :barcode,
						:within => 1..15, 
						:too_short => "Código de barras tem que ter no mínimo 1 caracteres",
				  		:too_long => "Código de barras tem que ter no máximo 15 caracteres"
	validates :barcode, :presence => { :message => "Informe o código de barras do livro"}
	
	include PgSearch
	pg_search_scope :search_full_text, 
	                :against => [:title, :author_one, :publisher], 
	                :using => { 
	                	:tsearch => {:prefix => true, :any_word => true}
	                    }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :set_book, only: [:show]

	def index
		search_book(params[:book_search])
		@book_search = params[:book_search]
	end

	def show
		unless @book.condition_deactivate 
			@schedules = @book.schedules
		else
			redirect_to books_path
		end
	end

	private 
	def set_book
		@book = Book.find(params[:id])
	end

	def book_params
		params.require(:book).permit(:author_one, :author_two, :author_three, :title,
		 :subtitle, :publisher, :year, :city, :edition, :volume, :pages, :ISBN, :barcode)
	end

	def search_book(book_search)
		if !book_search.blank?
			@books = Book.where(condition_deactivate: false).search_full_text("#{book_search}")
		else
			@books = Book.where(condition_deactivate: false)
		end
	end
end

app/views/books/index.html.erb
<div class="">
    <div class="page-title">
        <div class="title_left">
            <h3>Livros</h3>
        </div>
    </div>
    <%= form_tag books_post_path, method: :post do %>
    <div class="title_right">
        <div class="col-md-4 col-sm-12 col-xs-12 form-group pull-right top_search">
            <div class="input-group">
                <%= text_field_tag :book_search, @book_search, class: "form-control input-md", placeholder: "Título, Autor, Editora..."%>
                <span class="input-group-btn">
                <button class="btn btn-default" type="submit"> <i class="fa fa-search" aria-hidden="true"></i> </button>
                </span>
            </div>
        </div>
    </div>
    <%end%>
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md- col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Consulta de Livro</h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <h6 class="pull-right"><span class = "badge"><%=@books.count%></span></h6>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                    <thead>
                        <tr>
                            <th>Disponibilidade</th>
                            <th>Título</th>
                            <th>Primeiro Autor</th>
                            <th>Editora</th>
                            <th>Ano</th>
                            <th>Edição</th>
                            <th>Volume</th>
                            <th class="td-actions"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @books.each do |book| %>
                        <tr>
                            <td><%if !book.available%><i class="fa fa-times-circle" aria-hidden="true" style="color:red;"></i>
                            <%elsif book.schedules.size > 0%><i class="fa fa-exclamation-triangle"  aria-hidden="true" style="color:yellow;"></i>
                            <% else %><i class="fa fa-check-circle" aria-hidden="true" style="color:green;"></i><%end%></td>
                            <td><%= book.title %></td>
                            <td><%= book.author_one %></td>
                            <td><%= book.publisher %></td>
                            <td><%= book.year %></td>
                            <td><%= book.edition %></td>
                            <td><%= book.volume %></td>
                            <td><a href="<%= book_path book%>" class="btn btn-sm btn-primary"%><i class="fa fa-eye" aria-hidden="true"></i> Ver</a>
                        </tr>
                        <% end %>
                    </tbody>
                </table>
                <br>
            </div>
        </div>
    </div>
</div>
<br/>
<br/>
</div>

app/views/books/show.html.erb
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Livros</h3>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md- col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Consulta de Livro</h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <br />
                        <div class="row">
                            <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                                <p><strong>Disponibilidade</strong></p>
                                <p>
                                <%if !@book.available || @book.schedules.size > 0%>
                                <i class="fa fa-times-circle" aria-hidden="true" style="color:red;"></i>
                                <%else %>
                                <i class="fa fa-check-circle" aria-hidden="true" style="color:green;"></i>
                                <%end%></p>
                            </div>
                            <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                                <p><strong>Título</strong></p>
                                <p><%= @book.title%></p>
                            </div>
                            <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                                <p><strong>Subtítulo</strong></p>
                                <p><%= @book.subtitle%></p>
                            </div>
                        </div>
                        <hr />
                        <div class="row">
                            <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                                <p><strong>Primeiro Autor</strong></p>
                                <p><%= @book.author_one%></p>
                            </div>
                            <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                                <p><strong>Segundo Autor</strong></p>
                                <p><%= @book.author_two%></p>
                            </div>
                            <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                                <p><strong>Terceiro Autor</strong></p>
                                <p><%= @book.author_three%></p>
                            </div>
                        </div>
                        <hr />
                        <div class="row">
                            <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                                <p><strong>Editora</strong></p>
                                <p><%= @book.publisher%></p>
                            </div>
                            <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                                <p><strong>Ano</strong></p>
                                <p><%= @book.year%></p>
                            </div>
                            <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                                <p><strong>Local</strong></p>
                                <p><%= @book.city%></p>
                            </div>
                            <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                                <p><strong>Edição</strong></p>
                                <p><%= @book.edition%></p>
                            </div>
                            <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                                <p><strong>Volume</strong></p>
                                <p><%= @book.volume%></p>
                            </div>
                            <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                                <p><strong>Páginas</strong></p>
                                <p><%= @book.pages%></p>
                            </div>
                        </div>
                        <hr />
                        <div class="row">
                            <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                                <p><strong>ISBN</strong></p>
                                <p><%= @book.ISBN%></p>
                            </div>
                            <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                                <p><strong>Código de Barras</strong></p>
                                <p><%= @book.barcode%></p>
                            </div>
                        </div>
                    </div>
                    <div id="actions" class="row">
                      <div class="pull-right">
                        <div class="col-md-12">
                          <%= link_to '<i class="fa fa-long-arrow-left" aria-hidden="true"></i> Voltar</a>'.html_safe, :back, class: "btn btn-sm btn-default" %>
                            <% if @book.available %>
                                <a href="<%=new_loan_path @book.id%>" class="btn btn-sm btn-success"><i class="fa fa-hand-lizard-o" aria-hidden="true"></i> Solicitar Empréstimo</a>
                            <% else %>
                                <a href="#" class="btn btn-sm btn-default disabled" disabled="true"><i class="fa fa-hand-lizard-o" aria-hidden="true"></i> Solicitar Empréstimo</a>
                            <% end %>
                        </div>
                      </div>
                    </div>
                </div>
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Próximo Agendamento para este livro</h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <h6 class="pull-right"><span class = "badge" style="color: white;">Total de Agendamentos: <%=@schedules.count%></span></h6>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="dataTable_wrapper">
                        <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                            <thead>
                                <tr>
                                    <th width="50%">Data Início (provável)</th>
                                    <th width="50%">Data Devolução (provável)</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <% @schedules.limit(1).each do |schedule| %>
                                    <td><%= schedule.start_date %></td>
                                    <td><%= schedule.end_date %></td>
                                    <%end%>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>