config/routes.rb
Rails.application.routes.draw do
	root 'books#index'

	#books
	get 'books' => 'books#index', :as => 'books'
	post 'books' => 'books#index', :as => 'books_post'

	#loans
	post 'loans/create/:book_id	' => 'loans#create', :as => 'create_loan'
	get 'loans/new/:book_id' => 'loans#new', :as => 'new_loan'
	get 'loans/index' => 'loans#index', :as => 'loan_index'
	post 'loans/pre_return_book' => 'loans#pre_return_book', :as => 'loans_pre_return_book'
	post'loans/return_book' => 'loans#return_book', :as => 'loans_return_book'
	get 'loans' => 'loans#index', :as => 'loans'
	get 'return_robot/:case_id' => 'loans#return_robot', :as =>'return_robot'

	#robot
	get 'wait_robot/:case_id' => 'robot#wait_robot', :as =>'wait_robot'
	

	resources :books, except:[:index, :create, :update, :destroy]
end

app/models/loan.rb
class Loan < ApplicationRecord
	belongs_to :book
	belongs_to :user
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController

	include LoansHelper

	def new
		@loan = Loan.new
		@book = Book.find(params[:book_id])
	end

	def create
		@loan = false
		book = Book.find(params[:book_id])
		@user = User.find_by(matricula: params[:loan_context][:matricula])
		if @user.nil? || !@user.authenticate(params[:loan_context][:password])
			redirect_to new_loan_path book.id
			flash[:warning] = 'Matrícula ou senha inválidos!'
		else 
			if !is_defaulting_user?
				if book.available && (book.schedules.empty? || first_schedule_user?(book, @user))
					@loan = Loan.new
					@loan.book_id = book.id
					@loan.user_id = @user.id
					@loan.loan_date = Time.now
					@loan.return_date = Time.now + 15.days
					book_case = Case.find(book.case.id)
					#request_to_raspberry(:get, book.case.x_position , book.case.y_position)
					if @loan.save
						book.update_attribute(:available, false)
						free_case(book)
						if first_schedule_user?(book, @user)
							if book.schedules.first.user_id == @user.id
								book.schedules.first.destroy
							end
						end
						redirect_to wait_robot_path book_case.id
						flash[:success] = 'Empréstimo solicitado. O período máximo para a devolução do livro é: '+@loan.return_date.to_s
						UserNotifierMailer.send_email_to_loaded(@loan.user, @loan, @loan.book).deliver_now
					else
						redirect_to book
						flash[:warning] = 'Não foi possível solicitar o empréstimo'
						
					end
				else
					if !book.available
						flash[:info] = "Livro já emprestado"
					end
					if !book.schedules.empty? && !first_schedule_user?(book, @user)
						flash[:warning] = "Este livro está agendado para outro usuário"
					end
					
					redirect_to book
				end
			else
				redirect_to '/'
				flash[:warning] = 'Você está inadiplente! Devolva os livros atrasados para realizar novos empréstimos'
			end
		end
	end

	def index
	end

	def pre_return_book
		@user = User.find_by(matricula: params[:user][:matricula])
		if @user.nil? || !@user.authenticate(params[:user][:password])
			redirect_to loan_index_path
			flash[:warning] = 'Matrícula ou senha inválidos!'
		end
	end

	def return_book
		@user = User.find(params[:user_id])

		if @user.nil?
			redirect_to loan_index_path
			flash[:warning] = 'Erro. Usuário não encontrado!'
		else
			book = Book.find_by(barcode: params[:return_book][:barcode])
			if book.nil?
				redirect_to loan_index_path
				flash[:warning] = 'Livro não encontrado!'
			else
				@user.loans.each do |loan|
					if loan.book_id == book.id && loan.real_return_date == nil
						if set_case(book)

							loan.update_attribute(:real_return_date, Time.now)
							book.update_attribute(:available, true)
							set_schedules(book)
							#request_to_raspberry(:get, book.case.x_position, book.case.y_position)
							redirect_to wait_robot_path book.case.id
							flash[:success] = 'Livro devolvido com sucesso'
							return
						else
							flash[:warnig] = 'Operação cancelada! Não existe case disponível para o livro!'
							redirect_to loan_index_path
						end
					end
				end
				flash[:warning] = 'Você não possui um empréstimo registrado desse livro'
				redirect_to loan_index_path
			end
		end		 
	end

	def return_robot
		puts("$" * 80)
		puts("Case id: " + params[:case_id])
		book_case = Case.find(params[:case_id])
		#request_to_raspberry(:get, book_case.x_position, book_case.y_position)
		redirect_to books_path
	end

	
	
	private 

	def set_schedules(book)
		if !book.schedules.empty?
			first_schedule = book.schedules.first
			first_schedule.start_date = Time.now + 1.day
			first_schedule.end_date = Time.now + 15.days
		end
	end

	def free_case(book)
		case_book = Case.find(book.case_id)
		case_book.update_attribute(:book_id, nil)
		book.update_attribute(:case_id, nil)
	end

	def set_case(book)
		case_book = Case.find_by(book_id: nil)
		if !case_book.nil?
			case_book.update_attribute(:book_id, book.id)
			book.update_attribute(:case_id, case_book.id)
			return true
		else
			return false
		end
	end

end

app/helpers/loans_helper.rb
module LoansHelper
  def commands
    { get: 'a', put: 'b' }
  end

	def request_to_raspberry(cmd, x, y)
    message = "#{commands[cmd]}#{x.chr}#{y.chr}"
    puts "message = #{message}"
		Rails.tcp_socket.print(message)
	end
end

app/views/loans/index.html.erb
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Devolução</h3>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md- col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Devolução do Livro</h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                      <br />
                      <%= form_for :user, url: loans_pre_return_book_path, html: {class: "form-horizontal form-label-left input_mask"} do |f| %>
                      <div class="row">
                        <div class="col-md-3 col-sm-2 col-xs-12 form-group ">
                          <%= f.label :matricula,"Matrícula*"%>
                          <%= f.text_field :matricula, class: 'form-control', placeholder: 'Somente números', minlength: '9', required: ''%>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                        <%= f.label :password,"Senha*"%>
                        <%= f.password_field :password, class: 'form-control',minlength: '6', maxlength: '15', required: ''%>
                        </div>
                      </div>
                      <br />
                      <div class="pull-right">
                          <div class="btn-block">
                            <%= link_to '<i class="fa fa-long-arrow-left" aria-hidden="true"></i> Voltar</a>'.html_safe, :back, class: "btn btn-md btn-default" %>
                            <button class="btn btn-primary" type="reset">Resetar</button>
                            <%= f.submit "Enviar", class: 'btn btn-success'%>
                          </div>
                        </div>
                      <% end%>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/loans/new.html.erb
<div class="">
  <div class="page-title">
    <div class="title_left">

      <h3>Solicitar Livro</h3>
    </div>
  </div>
  <div class="clearfix"></div>
  <div class="row">
    <div class="col-md- col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>Informe seus dados</h2>
          <ul class="nav navbar-right panel_toolbox">
            <li class="pull-right"><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <br />
          <%= form_for :loan_context, url: create_loan_path, html: {class: "form-horizontal form-label-left input_mask"} do |f| %>
          <div class="row">
            <div class="col-md-3 col-sm-2 col-xs-12 form-group ">
              <%= f.label :matricula,"Matrícula*"%>
              <%= f.text_field :matricula, class: 'form-control', placeholder: 'Somente números', minlength: '9', required: ''%>
            </div>
            <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
            <%= f.label :password,"Senha*"%>
            <%= f.password_field :password, class: 'form-control',minlength: '6', maxlength: '15', required: ''%>
          </div>
            <%= hidden_field_tag :book_id, "#{params[:book_id]}" %>
          </div>
          <div class="ln_solid"></div>
          <div class="pull-right">
            <div class="btn-block">
              <%= link_to '<i class="fa fa-long-arrow-left" aria-hidden="true"></i> Voltar</a>'.html_safe, :back, class: "btn btn-md btn-default" %>
              <button class="btn btn-primary" type="reset">Resetar</button>
              <%= f.submit "Enviar", class: 'btn btn-success'%>
            </div>
          </div>
          <% end%>
        </div>
      </div>
    </div>
  </div>
 </div>

app/views/loans/pre_return_book.html.erb
<div class="">
  <div class="page-title">
    <div class="title_left">
      <h3>Devolver Livro</h3>
    </div>
  </div>
  <div class="clearfix"></div>
  <div class="row">
    <div class="col-md- col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>Informe o código de barras do livro</h2>
          <ul class="nav navbar-right panel_toolbox">
            <li class="pull-right"><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <br />
          <%= form_for :return_book, url: loans_return_book_path, html: {class: "form-horizontal form-label-left input_mask"} do |f| %>
          <div class="row">
            <div class="col-md-3 col-sm-2 col-xs-12 form-group ">
              <%= f.label :bar_code,"Código de Barras*"%>
              <%= f.text_field :barcode, class: 'form-control', placeholder: 'Somente números', minlength: '1', maxlength: '15', required: ''%>
            </div>
            </div>
            <%= hidden_field_tag :user_id, @user.id %>
          </div>
          <div class="ln_solid"></div>
          <div class="pull-right">
            <div class="btn-block">
              <%= link_to '<i class="fa fa-long-arrow-left" aria-hidden="true"></i> Voltar</a>'.html_safe, :back, class: "btn btn-md btn-default" %>
              <button class="btn btn-primary" type="reset">Resetar</button>
              <%= f.submit "Enviar", class: 'btn btn-success'%>
            </div>
          </div>
          <% end%>
        </div>
      </div>
    </div>
  </div>
 </div>